List<String> famousPeople = [
  "Peppa Pig",
  "Bob Esponja",
  "Pikachu",
  "Elsa (Frozen)",
  "Spiderman",
  "Ladybug (Miraculous)",
  "Chase (Paw Patrol)",
  "Goku",
  "Bluey",
  "Dora la Exploradora",
  "Mickey Mouse",
  "Minion (Kevin)",
  "Moana (Vaiana)",
  "Anna (Frozen)",
  "Marshall (Paw Patrol)",
  "Ash Ketchum (Pokémon)",
  "Rapunzel",
  "Batman (versión Lego o animada)",
  "Shin Chan",
  "Barbie",
  "Capitán América",
  "Hulk",
  "Thor",
  "Batman",
  "Superman",
  "Wonder Woman",
  "Scooby Doo",
  "Pocoyó",
  "Goku",
  "Pikachu"
];
