// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTGBIZHIkRpHVZCcd7qF0Du80fotPl52g',
    appId: '1:117964674054:android:93de55f743580a46675f87',
    messagingSenderId: '117964674054',
    projectId: 'padelhub-santa-barbara',
    authDomain: 'padelhub-santa-barbara.firebaseapp.com',
    storageBucket: 'padelhub-santa-barbara.appspot.com',
    measurementId: 'G-FH2CYJNMC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTGBIZHIkRpHVZCcd7qF0Du80fotPl52g',
    appId: '1:117964674054:android:93de55f743580a46675f87',
    messagingSenderId: '117964674054',
    projectId: 'padelhub-santa-barbara',
    storageBucket: 'padelhub-santa-barbara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGBIZHIkRpHVZCcd7qF0Du80fotPl52g',
    appId: '1:117964674054:android:93de55f743580a46675f87',
    messagingSenderId: '117964674054',
    projectId: 'padelhub-santa-barbara',
    storageBucket: 'padelhub-santa-barbara.appspot.com',
    iosClientId:
        '117964674054-tfdbsg9k4unragiav198do65083b4gn3.apps.googleusercontent.com',
    iosBundleId: 'com.zwymobile.whoishe',
  );
}
